kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-1
  labels:
    name: app-1
    purpose: ingress

spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-1
      purpose: ingress

  template:
    metadata:

      labels:
        name: app-1
        purpose: ingress
      
    spec:
      containers:
      - name: nginx
        image: pudviks/nginx:1.0
---

apiVersion: v1
kind: Service
metadata:
  name: app-1
spec:
  selector:
    name: app-1
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    # kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/group.name: pudviks
spec:
  ingressClassName: alb
  rules:
  - host: "app1.daws78s.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-1
            port:
              number: 80
  

    

    





